export type PoliticalLeaning =
  | 'progressive'
  | 'center_left'
  | 'center'
  | 'center_right'
  | 'conservative'
  | 'unknown';

export const sourceToPoliticalLeaning: Record<string, PoliticalLeaning> = {
  // === KONSERWATYWNE / PRAWICOWE (Conservative) ===
  'wPolityce.pl': 'conservative',
  'wpolityce.pl': 'conservative',
  'DoRzeczy': 'conservative',
  'dorzeczy.pl': 'conservative',
  'Do Rzeczy': 'conservative',
  'Niezalezna.pl': 'conservative',
  'niezalezna.pl': 'conservative',
  'NIEZALEZNA.PL': 'conservative',
  'GazetaPolska': 'conservative',
  'gazetapolska.pl': 'conservative',
  'Gazeta Polska': 'conservative',
  'wSieci': 'conservative',
  'wsieci.pl': 'conservative',
  'Nasz Dziennik': 'conservative',
  'naszdziennik.pl': 'conservative',
  'PCh24': 'conservative',
  'pch24.pl': 'conservative',
  'MediaNarodowe': 'conservative',
  'medianarodowe.com': 'conservative',
  'Fronda': 'conservative',
  'fronda.pl': 'conservative',

  // === CENTRO-PRAWICOWE (Center-Right) ===
  'Rzeczpospolita': 'center_right',
  'rp.pl': 'center_right',
  'Dziennik Gazeta Prawna': 'center_right',
  'gazetaprawna.pl': 'center_right',
  'www.gazetaprawna.pl': 'center_right',
  'Forbes.pl': 'center_right',
  'forbes.pl': 'center_right',

  // === CENTROWE (Center) ===
  'PAP': 'center',
  'pap.pl': 'center',
  'Polsat News': 'center',
  'polsatnews.pl': 'center',
  'Polskie Radio': 'center',
  'polskieradio.pl': 'center',
  'RMF FM': 'center',
  'rmf24.pl': 'center',
  'RMF24': 'center',
  'rmf24': 'center',
  'Radio ZET': 'center',
  'radiozet.pl': 'center',
  'wiadomosci.radiozet.pl': 'center',
  'radiogdansk.pl': 'center',
  'WP': 'center',
  'wp.pl': 'center',
  'WP.pl': 'center',
  'wiadomosci.wp.pl': 'center',
  'sportowefakty.wp.pl': 'center',
  'film.wp.pl': 'center',
  'Interia': 'center',
  'interia.pl': 'center',
  'Interia.pl': 'center',
  'wydarzenia.interia.pl': 'center',
  'sport.interia.pl': 'center',
  'biznes.interia.pl': 'center',
  'Interia.pl - Biznes': 'center',
  'Money.pl': 'center',
  'money.pl': 'center',
  'Bankier.pl': 'center',
  'bankier.pl': 'center',
  'Business Insider': 'center',
  'businessinsider.com.pl': 'center',
  'Puls Biznesu': 'center',
  'pb.pl': 'center',
  'Parkiet': 'center',
  'parkiet.com': 'center',
  'forsal.pl': 'center',
  'www.portalspozywczy.pl': 'center',
  'portalspozywczy.pl': 'center',
  'www.farmer.pl': 'center',
  'farmer.pl': 'center',
  'Fakt': 'center',
  'fakt.pl': 'center',
  'Fakt.pl': 'center',
  'FAKT24.pl': 'center',
  'Super Express': 'center',
  'se.pl': 'center',
  "Spider's Web": 'center',
  'spidersweb.pl': 'center',
  'WNP.pl': 'center',
  'wnp.pl': 'center',
  'Antyweb': 'center',
  'antyweb.pl': 'center',
  'Puls HR': 'center',
  'pulshr.pl': 'center',
  'PulsHR': 'center',
  'pulshr': 'center',
  'Culture.pl': 'center',
  'culture.pl': 'center',
  'Filmweb': 'center',
  'filmweb.pl': 'center',
  'Pomponik': 'center',
  'pomponik.pl': 'center',
  'Groszki.pl': 'center',
  'Wirtualne Media': 'center',
  'wirtualnemedia.pl': 'center',
  'Przeglad Sportowy': 'center',
  'przegladsportowy.pl': 'center',
  'przegladsportowy.onet.pl': 'center',
  'www.polsatsport.pl': 'center',
  'polsatsport.pl': 'center',
  'Dziennik Zachodni': 'center',
  'dziennikzachodni.pl': 'center',
  'Gazeta Krakowska': 'center',
  'gazetakrakowska.pl': 'center',
  'Gazeta Pomorska': 'center',
  'pomorska.pl': 'center',
  'Glos Wielkopolski': 'center',
  'gloswielkopolski.pl': 'center',
  'Dziennik Lodzki': 'center',
  'dzienniklodzki.pl': 'center',
  'Dziennik Baltycki': 'center',
  'dziennikbaltycki.pl': 'center',
  'Dziennik Polski': 'center',
  'dziennikpolski24.pl': 'center',
  'Express Ilustrowany': 'center',
  'expressilustrowany.pl': 'center',
  'Gazeta Olsztynka': 'center',
  'gazetaolsztynska.pl': 'center',
  'Warszawa Nasze Miasto': 'center',
  'warszawa.naszemiasto.pl': 'center',
  'Poznan Nasze Miasto': 'center',
  'poznan.naszemiasto.pl': 'center',
  'Gdansk Nasze Miasto': 'center',
  'gdansk.naszemiasto.pl': 'center',
  'Wroclaw Nasze Miasto': 'center',
  'wroclaw.naszemiasto.pl': 'center',
  'Szczecinek Nasze Miasto': 'center',
  'szczecinek.naszemiasto.pl': 'center',
  'Ketrzyn Nasze Miasto': 'center',
  'ketrzyn.naszemiasto.pl': 'center',
  'Zary Nasze Miasto': 'center',
  'zary.naszemiasto.pl': 'center',
  'epoznan.pl': 'center',
  'Dziennik': 'center',
  'wiadomosci.dziennik.pl': 'center',
  'AP News': 'center',
  'AP NEWS': 'center',
  'apnews.com': 'center',
  'Reuters': 'center',
  'reuters.com': 'center',
  'BBC': 'center',
  'BBC News': 'center',
  'bbc.com': 'center',
  'bbc.co.uk': 'center',
  'DW': 'center',
  'Deutsche Welle': 'center',
  'dw.com': 'center',
  'France 24': 'center',
  'France24': 'center',
  'france24.com': 'center',
  'Politico': 'center',
  'POLITICO': 'center',
  'politico.com': 'center',
  'Axios': 'center',
  'axios.com': 'center',

  // === CENTRO-LEWICOWE (Center-Left) ===
  'The Guardian': 'progressive',
  'theguardian.com': 'progressive',
  'New York Times': 'center_left',
  'The New York Times': 'center_left',
  'NYT': 'center_left',
  'nytimes.com': 'center_left',
  'Washington Post': 'center_left',
  'The Washington Post': 'center_left',
  'washingtonpost.com': 'center_left',
  'CNN': 'center_left',
  'cnn.com': 'center_left',
  'NPR': 'center_left',
  'npr.org': 'center_left',
  'The Atlantic': 'center_left',
  'theatlantic.com': 'center_left',
  'Al Jazeera': 'center_left',
  'Al Jazeera Online': 'center_left',
  'aljazeera.com': 'center_left',
  'TVP Info': 'center_left',
  'tvp.info': 'center_left',
  'Gazeta Wyborcza': 'progressive',
  'wyborcza.pl': 'progressive',
  'Newsweek': 'center_left',
  'newsweek.pl': 'center_left',
  'Polityka': 'center_left',
  'polityka.pl': 'center_left',
  'TVN24': 'center_left',
  'tvn24.pl': 'center_left',
  'Onet': 'center_left',
  'onet.pl': 'center_left',
  'Onet.pl': 'center_left',
  'Onet Wiadomosci': 'center_left',
  'wiadomosci.onet.pl': 'center_left',
  'Gazeta.pl': 'progressive',
  'gazeta.pl': 'progressive',
  'gazetapl': 'progressive',
  'wiadomosci.gazeta.pl': 'progressive',
  'NaTemat': 'progressive',
  'natemat.pl': 'progressive',
  'naTemat': 'progressive',
  'Wprost': 'center_left',
  'wprost.pl': 'center_left',
  'TOK FM': 'progressive',
  'tokfm.pl': 'progressive',

  // Centro-prawicowe zagraniczne
  'The Economist': 'center_right',
  'Economist': 'center_right',
  'economist.com': 'center_right',
  'Financial Times': 'center_right',
  'Financial Times News': 'center_right',
  'ft.com': 'center_right',
  'Bloomberg': 'center_right',
  'bloomberg.com': 'center_right',
  'Wall Street Journal': 'center_right',
  'The Wall Street Journal': 'center_right',
  'WSJ': 'center_right',
  'wsj.com': 'center_right',

  // === LIBERALNE / PROGRESYWNE (Progressive) ===
  'OKO.press': 'progressive',
  'oko.press': 'progressive',
  'Krytyka Polityczna': 'progressive',
  'krytykapolityczna.pl': 'progressive',
  'Przekroj': 'progressive',
  'Przekrój': 'progressive',
  'przekroj.pl': 'progressive',
  'Dwutygodnik': 'progressive',
  'dwutygodnik.com': 'progressive',

  // === Warianty z polskimi znakami ===
  'Przegląd Sportowy': 'center',
  'Głos Wielkopolski': 'center',
  'Dziennik Łódzki': 'center',
  'Dziennik Bałtycki': 'center',
  'Poznań Nasze Miasto': 'center',
  'Gdańsk Nasze Miasto': 'center',
  'Wrocław Nasze Miasto': 'center',
  'Kętrzyn Nasze Miasto': 'center',
  'Żary Nasze Miasto': 'center',
  'Onet Wiadomości': 'center_left',
  'Polska Agencja Prasowa': 'center',

  // === Nowe źródła ===
  'NCZAS.INFO': 'conservative',
  'nczas.info': 'conservative',
  'WaWa.info': 'center',
  'wawa.info': 'center',
  'Variety': 'center',
  'variety.com': 'center',
  'The Hollywood Reporter': 'center',
  'hollywoodreporter.com': 'center',
  'Sky News': 'center',
  'news.sky.com': 'center',
  'Euronews': 'center',
  'euronews.com': 'center',
  '24kurier.pl': 'center',
  '24Kurier.pl': 'center',
  'plotek.pl': 'center',
  'Plotek.pl': 'center',
  'Plotek': 'center',
  'wm.pl': 'center',
  'Nowa Trybuna Opolska': 'center',
  'nto.pl': 'center',
  'Deadline': 'center',
  'deadline.com': 'center',
  'netTG.pl': 'center',
  'nettg.pl': 'center',
  'Press.pl': 'center',
  'press.pl': 'center',
  'telepolis.pl': 'center',
  'Telepolis.pl': 'center',
  'Telepolis': 'center',
  'rdc.pl': 'center',
  'Warszawa i Mazowsze - najnowsze wiadomości w RDC': 'center',
  'RDC': 'center',
  'Lietuvos Radijas ir Televizija': 'center',
  'LRT': 'center',
  'lrt.lt': 'center',
  'propertynews.pl': 'center',
  'PropertyNews.pl': 'center',
  'www.dlahandlu.pl': 'center',
  'dlahandlu.pl': 'center',
  'www.portalsamorzadowy.pl': 'center',
  'portalsamorzadowy.pl': 'center',
  'Głos Koszaliński': 'center',
  'gk24.pl': 'center',
  'TechRadar': 'center',
  'techradar.com': 'center',
  'trojmiasto.pl': 'center',
  'Trojmiasto.pl': 'center',
  'www.sadyogrody.pl': 'center',
  'sadyogrody.pl': 'center',
  'Filary Biznesu': 'conservative',
  'filarybiznesu.pl': 'conservative',
  'energetyka24.com': 'center',
  'Energetyka24': 'center',
  'Strefa Biznesu': 'center',
  'strefabiznesu.pl': 'center',
  'HDTVPolska': 'center',
  'hdtvpolska.com': 'center',
  'wroclaw.tvp.pl': 'center_left',
  'NewsMed.pl': 'center',
  'newsmed.pl': 'center',
  'Centralne Biuro Śledcze Policji': 'center',
  'planeta.pl': 'center',
  'Planeta.pl': 'center',
  'kadry.infor.pl': 'center',
  'infor.pl': 'center',
  'INFOR.PL': 'center',
  'Rolling Stone': 'center_left',
  'rollingstone.com': 'center_left',
  'Vulture': 'center_left',
  'vulture.com': 'center_left',
  'meloradio.pl': 'center',
  'Meloradio': 'center',
  'Policja Lubuska': 'center',
  'Strefa Inwestorów': 'center',
  'strefainwestorow.pl': 'center',
  'cyberdefence24.pl': 'center',
  'CyberDefence24': 'center',
  'Policja Łódzka': 'center',
  'Policja.pl': 'center',
  'policja.pl': 'center',
  'o2.pl': 'center',
  'O2.pl': 'center',
  'o2': 'center',
  'Kobieta': 'center',
  'kobieta.wp.pl': 'center',
  'Nowy Tydzień - tygodnik lokalny na terenie powiatu chełmskiego, włodawskiego, krasnostawskiego oraz miasta Lublin i Świdnik': 'center',
  'Nowy Tydzień': 'center',
  'pudelek.pl': 'center',
  'Pudelek.pl': 'center',
  'Pudelek': 'center',
  'halotu.polsat.pl': 'center',
  'polsat.pl': 'center',
  'Polsat.pl': 'center',
  'Ars Technica': 'center',
  'arstechnica.com': 'center',
  'TechCrunch': 'center',
  'techcrunch.com': 'center',
  'The Verge': 'center',
  'theverge.com': 'center',
  'engadget': 'center',
  'Engadget': 'center',
  'engadget.com': 'center',
  'infosecurity24.pl': 'center',
  'InfoSecurity24': 'center',
  'Podróże': 'center',
  'podroze.wp.pl': 'center',
  'Tabletowo.pl': 'center',
  'tabletowo.pl': 'center',
  'BiznesAlert.pl': 'center',
  'biznesalert.pl': 'center',
  'Gizmodo': 'center',
  'gizmodo.com': 'center',
  'Kresy': 'conservative',
  'kresy.pl': 'conservative',
  'Kresy.pl': 'conservative',
  'wGospodarce.pl': 'conservative',
  'wgospodarce.pl': 'conservative',
  'MamBiznes.pl': 'center',
  'mambiznes.pl': 'center',
  'Wired': 'center_left',
  'wired.com': 'center_left',
  'Cyfrowa': 'center',
  'edziecko.pl': 'center',
  'Wydawnictwo militarne ZBIAM': 'center',
  'tuwroclaw.com': 'center',
  'Radio Wrocław': 'center',
  'radiowroclaw.pl': 'center',
  'Moto.pl': 'center',
  'moto.pl': 'center',
  'Nowiny': 'center',
  'nowiny24.pl': 'center',
  'Billboard': 'center',
  'billboard.com': 'center',
  'IndieWire': 'center_left',
  'indiewire.com': 'center_left',
  'The Next Web': 'center',
  'thenextweb.com': 'center',
  'Nauka w Polsce': 'center',
  'naukawpolsce.pl': 'center',
  'naukawpolsce.pap.pl': 'center',
  // Policja - instytucje rządowe
  'Komenda Miejska Policji w Koszalinie': 'center',
  'Policja Świętokrzyska': 'center',
  'Policja Dolnośląska': 'center',
  'Policja Warmińsko-Mazurska': 'center',
  'Policja Małopolska': 'center',
  'Policja Podkarpacka': 'center',
  'Policja Mazowiecka': 'center',
  'Policja Śląska': 'center',
  'Policja Wielkopolska': 'center',
  'Policja Pomorska': 'center',
  'Policja Podlaska': 'center',
  'Policja Zachodniopomorska': 'center',
  'Policja Opolska': 'center',
  'Policja Kujawsko-Pomorska': 'center',
  'Policja Lubelska': 'center',
  // Portale WP / polskie
  'Pogoda': 'center',
  'pogoda.wp.pl': 'center',
  // Polska Press regionalne
  'Gazeta Lubuska': 'center',
  'gazetalubuska.pl': 'center',
  'Kurier Lubelski': 'center',
  'kurierlubelski.pl': 'center',
  'Głos Szczeciński': 'center',
  'gs24.pl': 'center',
  'Kurier Poranny': 'center',
  'poranny.pl': 'center',
  'Echo Dnia': 'center',
  'echodnia.eu': 'center',
  'Nowości - Dziennik Toruński': 'center',
  'nowosci.com.pl': 'center',
  // Lokalne portale
  'Miejski Portal Informacyjny Bstok.pl Białystok': 'center',
  'bstok.pl': 'center',
  'zdrowiego.pl': 'center',
  'Gazeta Współczesna': 'center',
  'wspolczesna.pl': 'center',
  'Głos Pomorza': 'center',
  'gp24.pl': 'center',
  'stat.gov.pl': 'center',
  'GUS': 'center',
  'space24.pl': 'center',
  'Space24': 'center',
  'e-prawnik.pl': 'center',
  'ngo.pl': 'center',
  'NGO.pl': 'center',
  'ITwiz': 'center',
  'itwiz.pl': 'center',
  'Super Nowości24': 'center',
  'supernowosci24.pl': 'center',
  'Portal telekomunikacyjny Telix.pl': 'center',
  'telix.pl': 'center',
  'Telix.pl': 'center',
  'European Central Bank': 'center',
  'ecb.europa.eu': 'center',
  'gsmManiaK.pl': 'center',
  'gsmmaniak.pl': 'center',
  'benchmark.pl': 'center',
  'Benchmark.pl': 'center',
  'BlaskOnline Najlepsza rozrywka, plotki, lifestyle': 'center',
  'BlaskOnline': 'center',
  'blaskonline.pl': 'center',
  'vaticannews.va': 'center',
  'Vatican News': 'center',
  'Aleteia Polska': 'center_right',
  'aleteia.org': 'center_right',
  'KMP w Toruniu': 'center',
  'Rzecz o Innowacjach': 'center',
  'Strona Zdrowia': 'center',
  'stronazdrowia.pl': 'center',
  'topagrar.pl': 'center',
  'Top Agrar': 'center',
  'tygodnik-rolniczy.pl': 'center',
  'Tygodnik Rolniczy': 'center',

  // === Zagraniczne niszowe ===
  'tooofa.com': 'center',
  'América Digital': 'center',
  'america-digital.com': 'center',
  'publicar.argentina.indymedia.org': 'progressive',
  'argentina.indymedia.org': 'progressive',
  'Indymedia Argentina': 'progressive',
  'ZDNet': 'center',
  'ZDNET': 'center',
  'zdnet.com': 'center',
  'Andhrawatch': 'center',
  'andhrawatch.com': 'center',
  'Radio 90 FM': 'center',
  'eGospodarka.pl': 'center',
  'egospodarka.pl': 'center',
  'mjakmama24.pl': 'center',
  'dzieje.pl': 'center',
  'infowire.pl': 'center',
  'Life, For Instance': 'center',
  'lifeforinstance.com': 'center',
  'ARTnews.com': 'center',
  'artnews.com': 'center',
  'VentureBeat': 'center',
  'venturebeat.com': 'center',
};

export function getPoliticalLeaning(source: string): PoliticalLeaning {
  if (sourceToPoliticalLeaning[source]) {
    return sourceToPoliticalLeaning[source];
  }

  const lowercaseSource = source.toLowerCase();
  if (sourceToPoliticalLeaning[lowercaseSource]) {
    return sourceToPoliticalLeaning[lowercaseSource];
  }

  for (const [key, value] of Object.entries(sourceToPoliticalLeaning)) {
    if (source.includes(key) || key.includes(source)) {
      return value;
    }
    if (lowercaseSource.includes(key.toLowerCase()) || key.toLowerCase().includes(lowercaseSource)) {
      return value;
    }
  }

  return 'unknown';
}

export const allPoliticalLeanings: PoliticalLeaning[] = [
  'progressive', 'center_left', 'center', 'center_right', 'conservative', 'unknown'
];

/** Returns true if source has an explicit mapping (even if mapped to 'unknown') */
export function isPoliticalMapped(source: string): boolean {
  if (sourceToPoliticalLeaning[source]) return true;
  const lc = source.toLowerCase();
  if (sourceToPoliticalLeaning[lc]) return true;
  for (const key of Object.keys(sourceToPoliticalLeaning)) {
    if (source.includes(key) || key.includes(source)) return true;
    if (lc.includes(key.toLowerCase()) || key.toLowerCase().includes(lc)) return true;
  }
  return false;
}

export function politicalOrder(leaning: PoliticalLeaning): number {
  const order: Record<PoliticalLeaning, number> = {
    progressive: 0,
    center_left: 1,
    center: 2,
    center_right: 3,
    conservative: 4,
    unknown: 5,
  };
  return order[leaning];
}
