export type SourceNationality = 'polish' | 'american' | 'british' | 'irish' | 'german' | 'swiss_german' | 'swiss' | 'swedish' | 'french' | 'spanish' | 'italian' | 'austrian' | 'qatari' | 'lithuanian' | 'eu' | 'vatican' | 'canadian' | 'japanese' | 'portuguese' | 'romanian' | 'other';

export const sourceToNationality: Record<string, SourceNationality> = {
  // === POLSKIE (Polish capital) ===
  // Prawicowe
  'wPolityce.pl': 'polish',
  'wpolityce.pl': 'polish',
  'DoRzeczy': 'polish',
  'dorzeczy.pl': 'polish',
  'Do Rzeczy': 'polish',
  'DoRzeczy.pl': 'polish',
  'Niezalezna.pl': 'polish',
  'niezalezna.pl': 'polish',
  'NIEZALEZNA.PL': 'polish',
  'GazetaPolska': 'polish',
  'gazetapolska.pl': 'polish',
  'Gazeta Polska': 'polish',
  'wSieci': 'polish',
  'wsieci.pl': 'polish',
  'PCh24': 'polish',
  'pch24.pl': 'polish',
  'MediaNarodowe': 'polish',
  'medianarodowe.com': 'polish',
  'Fronda': 'polish',
  'fronda.pl': 'polish',
  'Nasz Dziennik': 'polish',
  'naszdziennik.pl': 'polish',

  // Panstwowe i publiczne
  'Rzeczpospolita': 'polish',
  'rp.pl': 'polish',
  'TVP Info': 'polish',
  'tvp.info': 'polish',
  'PAP': 'polish',
  'pap.pl': 'polish',
  'Polsat News': 'polish',
  'polsatnews.pl': 'polish',
  'Polskie Radio': 'polish',
  'polskieradio.pl': 'polish',
  'www.polsatsport.pl': 'polish',
  'polsatsport.pl': 'polish',

  // Wirtualna Polska (polskie)
  'WP': 'polish',
  'wp.pl': 'polish',
  'WP.pl': 'polish',
  'wiadomosci.wp.pl': 'polish',
  'sportowefakty.wp.pl': 'polish',
  'film.wp.pl': 'polish',

  // Interia (polskie - ZPR Media)
  'Interia': 'polish',
  'interia.pl': 'polish',
  'Interia.pl': 'polish',
  'wydarzenia.interia.pl': 'polish',
  'sport.interia.pl': 'polish',
  'biznes.interia.pl': 'polish',
  'Interia.pl - Biznes': 'polish',

  // Agora (polskie)
  'Gazeta Wyborcza': 'polish',
  'wyborcza.pl': 'polish',
  'Gazeta.pl': 'polish',
  'gazeta.pl': 'polish',
  'gazetapl': 'polish',
  'wiadomosci.gazeta.pl': 'polish',
  'TOK FM': 'polish',
  'tokfm.pl': 'polish',

  // Inne polskie
  'Money.pl': 'polish',
  'money.pl': 'polish',
  'Polityka': 'polish',
  'polityka.pl': 'polish',
  'OKO.press': 'polish',
  'oko.press': 'polish',
  'Krytyka Polityczna': 'polish',
  'krytykapolityczna.pl': 'polish',
  'Przekroj': 'polish',
  'przekroj.pl': 'polish',
  'Dwutygodnik': 'polish',
  'dwutygodnik.com': 'polish',
  'Radio ZET': 'polish',
  'radiozet.pl': 'polish',
  'wiadomosci.radiozet.pl': 'polish',
  'radiogdansk.pl': 'polish',
  'Dziennik Gazeta Prawna': 'polish',
  'gazetaprawna.pl': 'polish',
  'www.gazetaprawna.pl': 'polish',
  'Parkiet': 'polish',
  'parkiet.com': 'polish',
  'forsal.pl': 'polish',
  'Super Express': 'polish',
  'se.pl': 'polish',
  "Spider's Web": 'polish',
  'spidersweb.pl': 'polish',
  'WNP.pl': 'polish',
  'wnp.pl': 'polish',
  'Antyweb': 'polish',
  'antyweb.pl': 'polish',
  'Puls HR': 'polish',
  'pulshr.pl': 'polish',
  'PulsHR': 'polish',
  'pulshr': 'polish',
  'Culture.pl': 'polish',
  'culture.pl': 'polish',
  'Filmweb': 'polish',
  'filmweb.pl': 'polish',
  'Pomponik': 'polish',
  'pomponik.pl': 'polish',
  'Groszki.pl': 'polish',
  'Wirtualne Media': 'polish',
  'wirtualnemedia.pl': 'polish',
  'NaTemat': 'polish',
  'natemat.pl': 'polish',
  'naTemat': 'polish',
  'Wprost': 'polish',
  'wprost.pl': 'polish',
  'www.portalspozywczy.pl': 'polish',
  'portalspozywczy.pl': 'polish',
  'www.farmer.pl': 'polish',
  'farmer.pl': 'polish',
  'epoznan.pl': 'polish',
  'Dziennik': 'polish',
  'wiadomosci.dziennik.pl': 'polish',

  // Polska Press - Orlen (polskie panstwowe)
  'Dziennik Zachodni': 'polish',
  'dziennikzachodni.pl': 'polish',
  'Gazeta Krakowska': 'polish',
  'gazetakrakowska.pl': 'polish',
  'Gazeta Pomorska': 'polish',
  'pomorska.pl': 'polish',
  'Glos Wielkopolski': 'polish',
  'gloswielkopolski.pl': 'polish',
  'Dziennik Lodzki': 'polish',
  'dzienniklodzki.pl': 'polish',
  'Dziennik Baltycki': 'polish',
  'dziennikbaltycki.pl': 'polish',
  'Dziennik Polski': 'polish',
  'dziennikpolski24.pl': 'polish',
  'Express Ilustrowany': 'polish',
  'expressilustrowany.pl': 'polish',
  'Gazeta Olsztynka': 'polish',
  'gazetaolsztynska.pl': 'polish',

  // Nasze Miasto - Polska Press (polskie panstwowe - Orlen)
  'Warszawa Nasze Miasto': 'polish',
  'warszawa.naszemiasto.pl': 'polish',
  'Poznan Nasze Miasto': 'polish',
  'poznan.naszemiasto.pl': 'polish',
  'Gdansk Nasze Miasto': 'polish',
  'gdansk.naszemiasto.pl': 'polish',
  'Wroclaw Nasze Miasto': 'polish',
  'wroclaw.naszemiasto.pl': 'polish',
  'Szczecinek Nasze Miasto': 'polish',
  'szczecinek.naszemiasto.pl': 'polish',
  'Ketrzyn Nasze Miasto': 'polish',
  'ketrzyn.naszemiasto.pl': 'polish',
  'Zary Nasze Miasto': 'polish',
  'zary.naszemiasto.pl': 'polish',

  // === AMERYKANSKIE (American capital) ===
  // Warner Bros. Discovery
  'TVN24': 'american',
  'tvn24.pl': 'american',

  // Wire services
  'AP News': 'american',
  'AP NEWS': 'american',
  'apnews.com': 'american',

  // US mainstream media
  'New York Times': 'american',
  'The New York Times': 'american',
  'NYT': 'american',
  'nytimes.com': 'american',
  'Washington Post': 'american',
  'The Washington Post': 'american',
  'washingtonpost.com': 'american',
  'CNN': 'american',
  'cnn.com': 'american',
  'NPR': 'american',
  'npr.org': 'american',
  'Politico': 'american',
  'POLITICO': 'american',
  'politico.com': 'american',
  'The Atlantic': 'american',
  'theatlantic.com': 'american',
  'Axios': 'american',
  'axios.com': 'american',
  'Bloomberg': 'american',
  'bloomberg.com': 'american',
  'Wall Street Journal': 'american',
  'The Wall Street Journal': 'american',
  'WSJ': 'american',
  'wsj.com': 'american',

  // === BRYTYJSKIE (British capital) ===
  'BBC': 'british',
  'BBC News': 'british',
  'bbc.com': 'british',
  'bbc.co.uk': 'british',
  'The Guardian': 'british',
  'theguardian.com': 'british',
  'The Economist': 'british',
  'Economist': 'british',
  'economist.com': 'british',

  // === BRYTYJSKIE (British - Thomson Reuters, London HQ) ===
  'Reuters': 'british',
  'reuters.com': 'british',

  // === JAPOŃSKIE (Japanese capital - Nikkei) ===
  'Financial Times': 'japanese',
  'Financial Times News': 'japanese',
  'ft.com': 'japanese',

  // === NIEMIECKIE (German capital) ===
  // Bauer Media Group
  'RMF FM': 'german',
  'rmf24.pl': 'german',
  'RMF24': 'german',
  'rmf24': 'german',
  // Deutsche Welle (German public broadcaster)
  'DW': 'german',
  'Deutsche Welle': 'german',
  'dw.com': 'german',

  // === FRANCUSKIE (French capital) ===
  'France 24': 'french',
  'France24': 'french',
  'france24.com': 'french',

  // === KATARSKIE (Qatari capital) ===
  'Al Jazeera': 'qatari',
  'Al Jazeera Online': 'qatari',
  'aljazeera.com': 'qatari',

  // === SZWAJCAR.-NIEM. (Swiss-German capital) ===
  // Ringier Axel Springer Polska
  'Onet': 'swiss_german',
  'onet.pl': 'swiss_german',
  'Onet.pl': 'swiss_german',
  'Onet Wiadomosci': 'swiss_german',
  'wiadomosci.onet.pl': 'swiss_german',
  'Newsweek': 'swiss_german',
  'newsweek.pl': 'swiss_german',
  'Fakt': 'swiss_german',
  'fakt.pl': 'swiss_german',
  'Fakt.pl': 'swiss_german',
  'FAKT24.pl': 'swiss_german',
  'Forbes.pl': 'swiss_german',
  'forbes.pl': 'swiss_german',
  'Business Insider': 'swiss_german',
  'businessinsider.com.pl': 'swiss_german',
  'Przeglad Sportowy': 'swiss_german',
  'Przegląd Sportowy': 'swiss_german',
  'przegladsportowy.pl': 'swiss_german',
  'przegladsportowy.onet.pl': 'swiss_german',

  // === SZWEDZKIE (Swedish capital) ===
  // Bonnier Group
  'Bankier.pl': 'swedish',
  'bankier.pl': 'swedish',
  'Puls Biznesu': 'swedish',
  'pb.pl': 'swedish',

  // === Dodatkowe warianty z polskimi znakami ===
  'Przekrój': 'polish',
  'Głos Wielkopolski': 'polish',
  'Dziennik Łódzki': 'polish',
  'Dziennik Bałtycki': 'polish',
  'Poznań Nasze Miasto': 'polish',
  'Gdańsk Nasze Miasto': 'polish',
  'Wrocław Nasze Miasto': 'polish',
  'Kętrzyn Nasze Miasto': 'polish',
  'Żary Nasze Miasto': 'polish',
  'Onet Wiadomości': 'swiss_german',
  'Polska Agencja Prasowa': 'polish',

  // === Nowe źródła ===
  'NCZAS.INFO': 'polish',
  'nczas.info': 'polish',
  'WaWa.info': 'polish',
  'wawa.info': 'polish',
  'Variety': 'american',
  'variety.com': 'american',
  'The Hollywood Reporter': 'american',
  'hollywoodreporter.com': 'american',
  'Sky News': 'british',
  'news.sky.com': 'british',
  'The Independent': 'british',
  'independent.co.uk': 'british',
  // Euronews - Alpac Capital (Portuguese) since 2022
  'Euronews': 'portuguese',
  'euronews.com': 'portuguese',
  '24kurier.pl': 'polish',
  '24Kurier.pl': 'polish',
  'plotek.pl': 'polish',
  'Plotek.pl': 'polish',
  'Plotek': 'polish',
  'wm.pl': 'polish',
  'Nowa Trybuna Opolska': 'polish',
  'nto.pl': 'polish',
  'Deadline': 'american',
  'deadline.com': 'american',
  'netTG.pl': 'polish',
  'nettg.pl': 'polish',
  'Press.pl': 'polish',
  'press.pl': 'polish',
  'telepolis.pl': 'polish',
  'Telepolis.pl': 'polish',
  'Telepolis': 'polish',
  'rdc.pl': 'polish',
  'Warszawa i Mazowsze - najnowsze wiadomości w RDC': 'polish',
  'RDC': 'polish',
  // === LITEWSKIE (Lithuanian capital - public broadcaster) ===
  'Lietuvos Radijas ir Televizija': 'lithuanian',
  'LRT': 'lithuanian',
  'lrt.lt': 'lithuanian',
  'propertynews.pl': 'polish',
  'PropertyNews.pl': 'polish',
  'www.dlahandlu.pl': 'polish',
  'dlahandlu.pl': 'polish',
  'www.portalsamorzadowy.pl': 'polish',
  'portalsamorzadowy.pl': 'polish',
  'Głos Koszaliński': 'polish',
  'gk24.pl': 'polish',
  'TechRadar': 'british',
  'techradar.com': 'british',
  'trojmiasto.pl': 'polish',
  'Trojmiasto.pl': 'polish',
  'www.sadyogrody.pl': 'polish',
  'sadyogrody.pl': 'polish',
  'Filary Biznesu': 'polish',
  'filarybiznesu.pl': 'polish',
  'energetyka24.com': 'polish',
  'Energetyka24': 'polish',
  'Strefa Biznesu': 'polish',
  'strefabiznesu.pl': 'polish',
  'HDTVPolska': 'polish',
  'hdtvpolska.com': 'polish',
  'wroclaw.tvp.pl': 'polish',
  'NewsMed.pl': 'polish',
  'newsmed.pl': 'polish',
  'Centralne Biuro Śledcze Policji': 'polish',
  'planeta.pl': 'polish',
  'Planeta.pl': 'polish',
  'kadry.infor.pl': 'polish',
  'infor.pl': 'polish',
  'INFOR.PL': 'polish',
  'Rolling Stone': 'american',
  'rollingstone.com': 'american',
  'Vulture': 'american',
  'vulture.com': 'american',
  'meloradio.pl': 'polish',
  'Meloradio': 'polish',
  'Policja Lubuska': 'polish',
  'Strefa Inwestorów': 'polish',
  'strefainwestorow.pl': 'polish',
  'cyberdefence24.pl': 'polish',
  'CyberDefence24': 'polish',
  'Policja Łódzka': 'polish',
  'Policja.pl': 'polish',
  'policja.pl': 'polish',
  'o2.pl': 'polish',
  'O2.pl': 'polish',
  'o2': 'polish',
  'Kobieta': 'polish',
  'kobieta.wp.pl': 'polish',
  'Nowy Tydzień - tygodnik lokalny na terenie powiatu chełmskiego, włodawskiego, krasnostawskiego oraz miasta Lublin i Świdnik': 'polish',
  'Nowy Tydzień': 'polish',
  'pudelek.pl': 'polish',
  'Pudelek.pl': 'polish',
  'Pudelek': 'polish',
  'halotu.polsat.pl': 'polish',
  'polsat.pl': 'polish',
  'Polsat.pl': 'polish',
  'Ars Technica': 'american',
  'arstechnica.com': 'american',
  'TechCrunch': 'american',
  'techcrunch.com': 'american',
  'The Verge': 'american',
  'theverge.com': 'american',
  'engadget': 'american',
  'Engadget': 'american',
  'engadget.com': 'american',
  'infosecurity24.pl': 'polish',
  'InfoSecurity24': 'polish',
  'Podróże': 'polish',
  'podroze.wp.pl': 'polish',
  'Tabletowo.pl': 'polish',
  'tabletowo.pl': 'polish',
  'BiznesAlert.pl': 'polish',
  'biznesalert.pl': 'polish',
  'Gizmodo': 'american',
  'gizmodo.com': 'american',
  'Kresy': 'polish',
  'kresy.pl': 'polish',
  'Kresy.pl': 'polish',
  'wGospodarce.pl': 'polish',
  'wgospodarce.pl': 'polish',
  'MamBiznes.pl': 'swedish',
  'mambiznes.pl': 'swedish',
  'Wired': 'american',
  'wired.com': 'american',
  'Cyfrowa': 'polish',
  'edziecko.pl': 'polish',
  'Wydawnictwo militarne ZBIAM': 'polish',
  'tuwroclaw.com': 'polish',
  'Radio Wrocław': 'polish',
  'radiowroclaw.pl': 'polish',
  'Moto.pl': 'polish',
  'moto.pl': 'polish',
  'Nowiny': 'polish',
  'nowiny24.pl': 'polish',
  'Billboard': 'american',
  'billboard.com': 'american',
  'IndieWire': 'american',
  'indiewire.com': 'american',
  // The Next Web - Tekpon (Romanian) since Dec 2025
  'The Next Web': 'romanian',
  'thenextweb.com': 'romanian',
  'Nauka w Polsce': 'polish',
  'naukawpolsce.pl': 'polish',
  'naukawpolsce.pap.pl': 'polish',
  // Policja - instytucje rządowe
  'Komenda Miejska Policji w Koszalinie': 'polish',
  'Policja Świętokrzyska': 'polish',
  'Policja Dolnośląska': 'polish',
  'Policja Warmińsko-Mazurska': 'polish',
  'Policja Małopolska': 'polish',
  'Policja Podkarpacka': 'polish',
  'Policja Mazowiecka': 'polish',
  'Policja Śląska': 'polish',
  'Policja Wielkopolska': 'polish',
  'Policja Pomorska': 'polish',
  'Policja Podlaska': 'polish',
  'Policja Zachodniopomorska': 'polish',
  'Policja Opolska': 'polish',
  'Policja Kujawsko-Pomorska': 'polish',
  'Policja Lubelska': 'polish',
  // Portale WP / polskie
  'Pogoda': 'polish',
  'pogoda.wp.pl': 'polish',
  // Polska Press regionalne
  'Gazeta Lubuska': 'polish',
  'gazetalubuska.pl': 'polish',
  'Kurier Lubelski': 'polish',
  'kurierlubelski.pl': 'polish',
  'Głos Szczeciński': 'polish',
  'gs24.pl': 'polish',
  'Kurier Poranny': 'polish',
  'poranny.pl': 'polish',
  'Echo Dnia': 'polish',
  'echodnia.eu': 'polish',
  'Nowości - Dziennik Toruński': 'polish',
  'nowosci.com.pl': 'polish',
  // Lokalne portale
  'Miejski Portal Informacyjny Bstok.pl Białystok': 'polish',
  'bstok.pl': 'polish',
  'zdrowiego.pl': 'polish',
  'Gazeta Współczesna': 'polish',
  'wspolczesna.pl': 'polish',
  'Głos Pomorza': 'polish',
  'gp24.pl': 'polish',
  'stat.gov.pl': 'polish',
  'GUS': 'polish',
  'space24.pl': 'polish',
  'Space24': 'polish',
  'e-prawnik.pl': 'polish',
  'ngo.pl': 'polish',
  'NGO.pl': 'polish',
  'ITwiz': 'polish',
  'itwiz.pl': 'polish',
  'Super Nowości24': 'polish',
  'supernowosci24.pl': 'polish',
  'Portal telekomunikacyjny Telix.pl': 'polish',
  'telix.pl': 'polish',
  'Telix.pl': 'polish',
  // === UE (EU institution) ===
  'European Central Bank': 'eu',
  'ecb.europa.eu': 'eu',
  'gsmManiaK.pl': 'polish',
  'gsmmaniak.pl': 'polish',
  'benchmark.pl': 'polish',
  'Benchmark.pl': 'polish',
  'BlaskOnline Najlepsza rozrywka, plotki, lifestyle': 'polish',
  'BlaskOnline': 'polish',
  'blaskonline.pl': 'polish',
  // === WATYKAN (Vatican) ===
  'vaticannews.va': 'vatican',
  'Vatican News': 'vatican',
  'Aleteia Polska': 'french',
  'aleteia.org': 'french',
  'KMP w Toruniu': 'polish',
  'Rzecz o Innowacjach': 'polish',
  'Strona Zdrowia': 'polish',
  'stronazdrowia.pl': 'polish',
  'topagrar.pl': 'german',
  'Top Agrar': 'german',
  'tygodnik-rolniczy.pl': 'polish',
  'Tygodnik Rolniczy': 'polish',
  'www.rynekzdrowia.pl': 'polish',
  'rynekzdrowia.pl': 'polish',
  'Rynek Zdrowia': 'polish',
  'gazetawarszawska.com': 'polish',
  'Gazeta Warszawska': 'polish',
  'Gazeta Wrocławska': 'polish',
  'gazetawroclawska.pl': 'polish',
  'krasnal24.com': 'polish',
  'Prosto z Opolskiego - Wiadomosci z Opola i Opolszczyzny.': 'polish',
  'prostozopolskiego.pl': 'polish',
  'bilgorajska.pl': 'polish',
  'Jastrząb Post': 'polish',
  'jastrzabpost.pl': 'polish',
  'krakow.tvp.pl': 'polish',
  'bialystok.tvp.pl': 'polish',
  'wiadomoscihandlowe.pl': 'polish',
  'Wiadomości Handlowe': 'polish',
  'Bayerischer Rundfunk': 'german',
  'br.de': 'german',
  'BRIEF.PL - Pierwsze źródło inspiracji w biznesie': 'polish',
  'BRIEF.PL': 'polish',
  'brief.pl': 'polish',
  'Komenda Stołeczna Policji': 'polish',
  'Log24.pl': 'polish',
  'log24.pl': 'polish',
  'eska.pl': 'polish',
  'Eska': 'polish',

  // === SZWAJCARSKIE (Swiss capital) - dodatkowe ===
  '20 Minuten': 'swiss',
  '20min.ch': 'swiss',

  // === FRANCUSKIE (French capital) - dodatkowe ===
  "LExpress.fr": 'french',
  "L'Express": 'french',
  'lexpress.fr': 'french',

  // === IRLANDZKIE (Irish capital) ===
  'The Irish Times': 'irish',
  'irishtimes.com': 'irish',
  'RTE.ie': 'irish',
  'RTE': 'irish',
  'rte.ie': 'irish',
  'Antymatrix': 'other',
  'Bljesak.info': 'other',
  'bljesak.info': 'other',

  // === Zagraniczne niszowe ===
  'tooofa.com': 'other',
  'América Digital': 'other',
  'america-digital.com': 'other',
  'publicar.argentina.indymedia.org': 'other',
  'argentina.indymedia.org': 'other',
  'Indymedia Argentina': 'other',
  'ZDNet': 'american',
  'ZDNET': 'american',
  'zdnet.com': 'american',
  'Andhrawatch': 'other',
  'andhrawatch.com': 'other',
  'Radio 90 FM': 'polish',
  'eGospodarka.pl': 'polish',
  'egospodarka.pl': 'polish',
  'mjakmama24.pl': 'polish',
  'dzieje.pl': 'polish',
  'infowire.pl': 'polish',
  'Life, For Instance': 'american',
  'lifeforinstance.com': 'american',
  'ARTnews.com': 'american',
  'artnews.com': 'american',
  'VentureBeat': 'american',
  'venturebeat.com': 'american',

  // === FRANCUSKIE (French capital) - prasa ===
  'Le Figaro': 'french',
  'Le Figaro.fr': 'french',
  'lefigaro.fr': 'french',
  '20 Minutes': 'french',
  '20minutes': 'french',
  '20minutes.fr': 'french',
  'Le Parisien': 'french',
  'leparisien.fr': 'french',

  // === HISZPAŃSKIE (Spanish capital) ===
  'La Vanguardia': 'spanish',
  'LaVanguardia': 'spanish',
  'lavanguardia.com': 'spanish',
  '20 minutos': 'spanish',
  '20minutos': 'spanish',
  '20minutos.es': 'spanish',
  'EL PAÍS': 'spanish',
  'El País': 'spanish',
  'elpais.com': 'spanish',
  'LaSexta': 'spanish',
  'lasexta.com': 'spanish',
  'ABC': 'spanish',
  'ABC ﻿TU DIARIO EN ESPAÑOL': 'spanish',
  'abc.es': 'spanish',

  // === NIEMIECKIE (German capital) - prasa ===
  'ZEIT ONLINE': 'german',
  'Die Zeit': 'german',
  'zeit.de': 'german',
  'Süddeutsche Zeitung': 'german',
  'Suddeutsche Zeitung': 'german',
  'sueddeutsche.de': 'german',

  // === FRANCUSKIE (French capital) - regionalne ===
  'Sud Ouest': 'french',
  'SudOuest.fr': 'french',
  'sudouest.fr': 'french',

  // === NIEMIECKIE (German capital) - magazyny ===
  'stern.de': 'german',
  'Stern': 'german',

  // === WŁOSKIE (Italian capital) ===
  'EL MUNDO': 'italian',
  'El Mundo': 'italian',
  'elmundo.es': 'italian',
  'ANSA.it': 'italian',
  'ANSA': 'italian',
  'ansa.it': 'italian',

  // === HISZPAŃSKIE (Spanish capital) - dodatkowe ===
  'europa press': 'spanish',
  'Europa Press': 'spanish',
  'europapress.es': 'spanish',
  'eldiario.es': 'spanish',
  'elDiario.es': 'spanish',
  'El Periódico': 'spanish',
  'El Periodico': 'spanish',
  'elperiodico.com': 'spanish',

  // === NIEMIECKIE (German capital) - dodatkowe ===
  'Der Tagesspiegel': 'german',
  'tagesspiegel.de': 'german',
  'N-tv': 'german',
  'n-tv': 'german',
  'n-tv.de': 'german',

  // === FRANCUSKIE (French capital) - dodatkowe ===
  'Franceinfo': 'french',
  'franceinfo': 'french',
  'francetvinfo.fr': 'french',
  'Le Monde': 'french',
  'Le Monde.fr': 'french',
  'lemonde.fr': 'french',
  'BFMTV': 'french',
  'bfmtv.com': 'french',
  "L'Opinion": 'french',
  'lopinion.fr': 'french',

  // === HISZPAŃSKIE (Spanish capital) - kolejne ===
  'RTVE.es': 'spanish',
  'RTVE': 'spanish',
  'rtve.es': 'spanish',
  'El Confidencial': 'spanish',
  'elconfidencial.com': 'spanish',
  'La Razón': 'spanish',
  'La Razon': 'spanish',
  'larazon.es': 'spanish',

  // === AUSTRIACKIE (Austrian capital) ===
  'der Standard': 'austrian',
  'Der Standard': 'austrian',
  'derstandard.at': 'austrian',
  'newsORF.at': 'austrian',
  'ORF': 'austrian',
  'orf.at': 'austrian',

  // === FRANCUSKIE (French capital) - kolejne ===
  'RFI': 'french',
  'rfi.fr': 'french',

  // === NIEMIECKIE (German capital) - kolejne ===
  'Handelsblatt': 'german',
  'handelsblatt.com': 'german',

  // === WŁOSKIE (Italian capital) - dodatkowe ===
  'Adnkronos': 'italian',
  'adnkronos.com': 'italian',
  'Tgcom24': 'italian',
  'tgcom24.mediaset.it': 'italian',
  'Il Messaggero': 'italian',
  'ilmessaggero.it': 'italian',
  'il Giornale.it': 'italian',
  'il Giornale': 'italian',
  'ilgiornale.it': 'italian',
  'Corriere della Sera': 'italian',
  'corriere.it': 'italian',

  // === SZWAJCARSKIE (Swiss capital) ===
  'Neue Zürcher Zeitung': 'swiss',
  'NZZ': 'swiss',
  'nzz.ch': 'swiss',
  'Le Temps': 'swiss',
  'letemps.ch': 'swiss',
  'watson.ch/': 'swiss',
  'watson.ch': 'swiss',

  // === NIEMIECKIE (German capital) - Axel Springer ===
  'DIE WELT': 'german',
  'Die Welt': 'german',
  'welt.de': 'german',
  'Frankfurter Allgemeine': 'german',
  'Frankfurter Allgemeine Zeitung': 'german',
  'FAZ': 'german',
  'faz.net': 'german',
  'Spiegel Online': 'german',
  'Der Spiegel': 'german',
  'spiegel.de': 'german',
  'Focus': 'german',
  'focus.de': 'german',
  'Wirtschafts Woche': 'german',
  'WirtschaftsWoche': 'german',
  'wiwo.de': 'german',
  'tagesschau.de': 'german',
  'Tagesschau': 'german',
  'Berliner Zeitung': 'german',
  'berliner-zeitung.de': 'german',
  'RP Online': 'german',
  'Rheinische Post': 'german',
  'rp-online.de': 'german',

  // === FRANCUSKIE (French capital) - kolejne ===
  'Courrier international': 'french',
  'courrierinternational.com': 'french',
  'Mediapart': 'french',
  'mediapart.fr': 'french',
  'Ouest France': 'french',
  'Ouest-France': 'french',
  'ouest-france.fr': 'french',

  // === WŁOSKIE (Italian capital) - kolejne ===
  'Fanpage': 'italian',
  'fanpage.it': 'italian',
  'La Repubblica': 'italian',
  'La Repubblica.it': 'italian',
  'repubblica.it': 'italian',
  'La Stampa': 'italian',
  'lastampa.it': 'italian',
  'Rai news': 'italian',
  'Rai News': 'italian',
  'rainews.it': 'italian',
  'Open': 'italian',
  'open.online': 'italian',
  'AGI': 'italian',
  'agi.it': 'italian',
  'Il Fatto Quotidiano': 'italian',
  'ilfattoquotidiano.it': 'italian',
  'Il Sole 24 ORE': 'italian',
  'Il Sole 24 Ore': 'italian',
  'ilsole24ore.com': 'italian',
};

export function getSourceNationality(source: string): SourceNationality {
  if (sourceToNationality[source]) {
    return sourceToNationality[source];
  }

  const lowercaseSource = source.toLowerCase();
  if (sourceToNationality[lowercaseSource]) {
    return sourceToNationality[lowercaseSource];
  }

  for (const [key, value] of Object.entries(sourceToNationality)) {
    if (source.includes(key) || key.includes(source)) {
      return value;
    }
    if (lowercaseSource.includes(key.toLowerCase()) || key.toLowerCase().includes(lowercaseSource)) {
      return value;
    }
  }

  return 'other';
}

/** ISO 3166-1 alpha-2 codes for flag-icons CSS library */
export const nationalityCodes: Record<SourceNationality, string | null> = {
  polish: 'pl',
  american: 'us',
  british: 'gb',
  irish: 'ie',
  german: 'de',
  swiss_german: 'ch',
  swiss: 'ch',
  swedish: 'se',
  french: 'fr',
  spanish: 'es',
  italian: 'it',
  austrian: 'at',
  qatari: 'qa',
  lithuanian: 'lt',
  eu: 'eu',
  vatican: 'va',
  canadian: 'ca',
  japanese: 'jp',
  portuguese: 'pt',
  romanian: 'ro',
  other: null,
};

export const nationalityLabels: Record<SourceNationality, { en: string; pl: string; de: string }> = {
  polish: { en: 'Polish', pl: 'Polskie', de: 'Polnisch' },
  american: { en: 'American', pl: 'Ameryka\u0144skie', de: 'Amerikanisch' },
  british: { en: 'British', pl: 'Brytyjskie', de: 'Britisch' },
  irish: { en: 'Irish', pl: 'Irlandzkie', de: 'Irisch' },
  german: { en: 'German', pl: 'Niemieckie', de: 'Deutsch' },
  swiss_german: { en: 'Swiss-German', pl: 'Szwajcar.-niem.', de: 'Schweiz.-dt.' },
  swiss: { en: 'Swiss', pl: 'Szwajcarskie', de: 'Schweizerisch' },
  swedish: { en: 'Swedish', pl: 'Szwedzkie', de: 'Schwedisch' },
  french: { en: 'French', pl: 'Francuskie', de: 'Französisch' },
  spanish: { en: 'Spanish', pl: 'Hiszpańskie', de: 'Spanisch' },
  italian: { en: 'Italian', pl: 'Włoskie', de: 'Italienisch' },
  austrian: { en: 'Austrian', pl: 'Austriackie', de: 'Österreichisch' },
  qatari: { en: 'Qatari', pl: 'Katarskie', de: 'Katarisch' },
  lithuanian: { en: 'Lithuanian', pl: 'Litewskie', de: 'Litauisch' },
  eu: { en: 'EU', pl: 'UE', de: 'EU' },
  vatican: { en: 'Vatican', pl: 'Watykan', de: 'Vatikan' },
  canadian: { en: 'Canadian', pl: 'Kanadyjskie', de: 'Kanadisch' },
  japanese: { en: 'Japanese', pl: 'Japońskie', de: 'Japanisch' },
  portuguese: { en: 'Portuguese', pl: 'Portugalskie', de: 'Portugiesisch' },
  romanian: { en: 'Romanian', pl: 'Rumuńskie', de: 'Rumänisch' },
  other: { en: 'Other', pl: 'Inne', de: 'Andere' },
};

export const allNationalities: SourceNationality[] = Object.keys(nationalityLabels) as SourceNationality[];

/** Returns true if source has an explicit mapping (even if mapped to 'other') */
export function isNationalityMapped(source: string): boolean {
  if (sourceToNationality[source]) return true;
  const lc = source.toLowerCase();
  if (sourceToNationality[lc]) return true;
  for (const key of Object.keys(sourceToNationality)) {
    if (source.includes(key) || key.includes(source)) return true;
    if (lc.includes(key.toLowerCase()) || key.toLowerCase().includes(lc)) return true;
  }
  return false;
}
